theme = "transparent"

[editor]
mouse = false
scrolloff = 999
line-number = "relative"  
bufferline = "multiple" # shows bufferline when more than one buffer   

# changes the cursor shape depending on the mode you're in. 
[editor.cursor-shape] 
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
 
[keys.insert]
j = { k = "normal_mode" } # Maps "fj" to exit insert mode
k = { j = "normal_mode" } # Maps "fj" to exit insert mode

[keys.normal]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

"n" = "move_char_left"


esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"

# for indent guides
[editor.indent-guides]
render = false
character = "|" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
